// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewWriterWrapper creates a new instance of WriterWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriterWrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *WriterWrapper {
	mock := &WriterWrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WriterWrapper is an autogenerated mock type for the WriterWrapper type
type WriterWrapper struct {
	mock.Mock
}

type WriterWrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *WriterWrapper) EXPECT() *WriterWrapper_Expecter {
	return &WriterWrapper_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type WriterWrapper
func (_mock *WriterWrapper) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WriterWrapper_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type WriterWrapper_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *WriterWrapper_Expecter) Close() *WriterWrapper_Close_Call {
	return &WriterWrapper_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *WriterWrapper_Close_Call) Run(run func()) *WriterWrapper_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WriterWrapper_Close_Call) Return(err error) *WriterWrapper_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WriterWrapper_Close_Call) RunAndReturn(run func() error) *WriterWrapper_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CloseWithError provides a mock function for the type WriterWrapper
func (_mock *WriterWrapper) CloseWithError(err error) error {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for CloseWithError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(error) error); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WriterWrapper_CloseWithError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseWithError'
type WriterWrapper_CloseWithError_Call struct {
	*mock.Call
}

// CloseWithError is a helper method to define mock.On call
//   - err error
func (_e *WriterWrapper_Expecter) CloseWithError(err interface{}) *WriterWrapper_CloseWithError_Call {
	return &WriterWrapper_CloseWithError_Call{Call: _e.mock.On("CloseWithError", err)}
}

func (_c *WriterWrapper_CloseWithError_Call) Run(run func(err error)) *WriterWrapper_CloseWithError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WriterWrapper_CloseWithError_Call) Return(err1 error) *WriterWrapper_CloseWithError_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *WriterWrapper_CloseWithError_Call) RunAndReturn(run func(err error) error) *WriterWrapper_CloseWithError_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type WriterWrapper
func (_mock *WriterWrapper) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WriterWrapper_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type WriterWrapper_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *WriterWrapper_Expecter) Write(p interface{}) *WriterWrapper_Write_Call {
	return &WriterWrapper_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *WriterWrapper_Write_Call) Run(run func(p []byte)) *WriterWrapper_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WriterWrapper_Write_Call) Return(n int, err error) *WriterWrapper_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *WriterWrapper_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *WriterWrapper_Write_Call {
	_c.Call.Return(run)
	return _c
}
