// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/service/history/queuev2 (interfaces: InMemQueue)
//
// Generated by this command:
//
//	mockgen -package queuev2 -destination queue_mem_mock.go github.com/uber/cadence/service/history/queuev2 InMemQueue
//

// Package queuev2 is a generated GoMock package.
package queuev2

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	persistence "github.com/uber/cadence/common/persistence"
)

// MockInMemQueue is a mock of InMemQueue interface.
type MockInMemQueue struct {
	ctrl     *gomock.Controller
	recorder *MockInMemQueueMockRecorder
	isgomock struct{}
}

// MockInMemQueueMockRecorder is the mock recorder for MockInMemQueue.
type MockInMemQueueMockRecorder struct {
	mock *MockInMemQueue
}

// NewMockInMemQueue creates a new mock instance.
func NewMockInMemQueue(ctrl *gomock.Controller) *MockInMemQueue {
	mock := &MockInMemQueue{ctrl: ctrl}
	mock.recorder = &MockInMemQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInMemQueue) EXPECT() *MockInMemQueueMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockInMemQueue) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockInMemQueueMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockInMemQueue)(nil).Clear))
}

// GetTasks mocks base method.
func (m *MockInMemQueue) GetTasks(inclusiveMinTaskKey, exclusiveMaxTaskKey persistence.HistoryTaskKey, predicate Predicate, pageSize int) ([]persistence.Task, persistence.HistoryTaskKey) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", inclusiveMinTaskKey, exclusiveMaxTaskKey, predicate, pageSize)
	ret0, _ := ret[0].([]persistence.Task)
	ret1, _ := ret[1].(persistence.HistoryTaskKey)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockInMemQueueMockRecorder) GetTasks(inclusiveMinTaskKey, exclusiveMaxTaskKey, predicate, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockInMemQueue)(nil).GetTasks), inclusiveMinTaskKey, exclusiveMaxTaskKey, predicate, pageSize)
}

// LTrim mocks base method.
func (m *MockInMemQueue) LTrim(newInclusiveMinTaskKey persistence.HistoryTaskKey) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LTrim", newInclusiveMinTaskKey)
}

// LTrim indicates an expected call of LTrim.
func (mr *MockInMemQueueMockRecorder) LTrim(newInclusiveMinTaskKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LTrim", reflect.TypeOf((*MockInMemQueue)(nil).LTrim), newInclusiveMinTaskKey)
}

// Len mocks base method.
func (m *MockInMemQueue) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockInMemQueueMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockInMemQueue)(nil).Len))
}

// LookAHead mocks base method.
func (m *MockInMemQueue) LookAHead(minTaskKey persistence.HistoryTaskKey) persistence.Task {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookAHead", minTaskKey)
	ret0, _ := ret[0].(persistence.Task)
	return ret0
}

// LookAHead indicates an expected call of LookAHead.
func (mr *MockInMemQueueMockRecorder) LookAHead(minTaskKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookAHead", reflect.TypeOf((*MockInMemQueue)(nil).LookAHead), minTaskKey)
}

// PutTasks mocks base method.
func (m *MockInMemQueue) PutTasks(tasks []persistence.Task) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PutTasks", tasks)
}

// PutTasks indicates an expected call of PutTasks.
func (mr *MockInMemQueueMockRecorder) PutTasks(tasks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutTasks", reflect.TypeOf((*MockInMemQueue)(nil).PutTasks), tasks)
}

// RTrimBySize mocks base method.
func (m *MockInMemQueue) RTrimBySize(maxSize int) (persistence.HistoryTaskKey, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RTrimBySize", maxSize)
	ret0, _ := ret[0].(persistence.HistoryTaskKey)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// RTrimBySize indicates an expected call of RTrimBySize.
func (mr *MockInMemQueueMockRecorder) RTrimBySize(maxSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RTrimBySize", reflect.TypeOf((*MockInMemQueue)(nil).RTrimBySize), maxSize)
}
