// Code generated by MockGen. DO NOT EDIT.
// Source: percentage_onboarded.go
//
// Generated by this command:
//
//	mockgen -package membership -source percentage_onboarded.go -destination percentage_onboarded_mock.go -self_package github.com/uber/cadence/common/membership
//

// Package membership is a generated GoMock package.
package membership

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPercentageOnboarded is a mock of PercentageOnboarded interface.
type MockPercentageOnboarded struct {
	ctrl     *gomock.Controller
	recorder *MockPercentageOnboardedMockRecorder
	isgomock struct{}
}

// MockPercentageOnboardedMockRecorder is the mock recorder for MockPercentageOnboarded.
type MockPercentageOnboardedMockRecorder struct {
	mock *MockPercentageOnboarded
}

// NewMockPercentageOnboarded creates a new mock instance.
func NewMockPercentageOnboarded(ctrl *gomock.Controller) *MockPercentageOnboarded {
	mock := &MockPercentageOnboarded{ctrl: ctrl}
	mock.recorder = &MockPercentageOnboardedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPercentageOnboarded) EXPECT() *MockPercentageOnboardedMockRecorder {
	return m.recorder
}

// Value mocks base method.
func (m *MockPercentageOnboarded) Value() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].(int)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockPercentageOnboardedMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockPercentageOnboarded)(nil).Value))
}
