// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/uber/cadence/common/elasticsearch/bulk"
)

// NewGenericBulkProcessor creates a new instance of GenericBulkProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenericBulkProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenericBulkProcessor {
	mock := &GenericBulkProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GenericBulkProcessor is an autogenerated mock type for the GenericBulkProcessor type
type GenericBulkProcessor struct {
	mock.Mock
}

type GenericBulkProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *GenericBulkProcessor) EXPECT() *GenericBulkProcessor_Expecter {
	return &GenericBulkProcessor_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type GenericBulkProcessor
func (_mock *GenericBulkProcessor) Add(request *bulk.GenericBulkableAddRequest) {
	_mock.Called(request)
	return
}

// GenericBulkProcessor_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type GenericBulkProcessor_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - request *bulk.GenericBulkableAddRequest
func (_e *GenericBulkProcessor_Expecter) Add(request interface{}) *GenericBulkProcessor_Add_Call {
	return &GenericBulkProcessor_Add_Call{Call: _e.mock.On("Add", request)}
}

func (_c *GenericBulkProcessor_Add_Call) Run(run func(request *bulk.GenericBulkableAddRequest)) *GenericBulkProcessor_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bulk.GenericBulkableAddRequest
		if args[0] != nil {
			arg0 = args[0].(*bulk.GenericBulkableAddRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GenericBulkProcessor_Add_Call) Return() *GenericBulkProcessor_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *GenericBulkProcessor_Add_Call) RunAndReturn(run func(request *bulk.GenericBulkableAddRequest)) *GenericBulkProcessor_Add_Call {
	_c.Run(run)
	return _c
}

// Close provides a mock function for the type GenericBulkProcessor
func (_mock *GenericBulkProcessor) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GenericBulkProcessor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type GenericBulkProcessor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *GenericBulkProcessor_Expecter) Close() *GenericBulkProcessor_Close_Call {
	return &GenericBulkProcessor_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *GenericBulkProcessor_Close_Call) Run(run func()) *GenericBulkProcessor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GenericBulkProcessor_Close_Call) Return(err error) *GenericBulkProcessor_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GenericBulkProcessor_Close_Call) RunAndReturn(run func() error) *GenericBulkProcessor_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Flush provides a mock function for the type GenericBulkProcessor
func (_mock *GenericBulkProcessor) Flush() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GenericBulkProcessor_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type GenericBulkProcessor_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
func (_e *GenericBulkProcessor_Expecter) Flush() *GenericBulkProcessor_Flush_Call {
	return &GenericBulkProcessor_Flush_Call{Call: _e.mock.On("Flush")}
}

func (_c *GenericBulkProcessor_Flush_Call) Run(run func()) *GenericBulkProcessor_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GenericBulkProcessor_Flush_Call) Return(err error) *GenericBulkProcessor_Flush_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GenericBulkProcessor_Flush_Call) RunAndReturn(run func() error) *GenericBulkProcessor_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type GenericBulkProcessor
func (_mock *GenericBulkProcessor) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GenericBulkProcessor_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type GenericBulkProcessor_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GenericBulkProcessor_Expecter) Start(ctx interface{}) *GenericBulkProcessor_Start_Call {
	return &GenericBulkProcessor_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *GenericBulkProcessor_Start_Call) Run(run func(ctx context.Context)) *GenericBulkProcessor_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GenericBulkProcessor_Start_Call) Return(err error) *GenericBulkProcessor_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GenericBulkProcessor_Start_Call) RunAndReturn(run func(ctx context.Context) error) *GenericBulkProcessor_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type GenericBulkProcessor
func (_mock *GenericBulkProcessor) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GenericBulkProcessor_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type GenericBulkProcessor_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *GenericBulkProcessor_Expecter) Stop() *GenericBulkProcessor_Stop_Call {
	return &GenericBulkProcessor_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *GenericBulkProcessor_Stop_Call) Run(run func()) *GenericBulkProcessor_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GenericBulkProcessor_Stop_Call) Return(err error) *GenericBulkProcessor_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GenericBulkProcessor_Stop_Call) RunAndReturn(run func() error) *GenericBulkProcessor_Stop_Call {
	_c.Call.Return(run)
	return _c
}
