// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/uber/cadence/common/persistence"
)

// NewHistoryV2Manager creates a new instance of HistoryV2Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHistoryV2Manager(t interface {
	mock.TestingT
	Cleanup(func())
}) *HistoryV2Manager {
	mock := &HistoryV2Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HistoryV2Manager is an autogenerated mock type for the HistoryManager type
type HistoryV2Manager struct {
	mock.Mock
}

type HistoryV2Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *HistoryV2Manager) EXPECT() *HistoryV2Manager_Expecter {
	return &HistoryV2Manager_Expecter{mock: &_m.Mock}
}

// AppendHistoryNodes provides a mock function for the type HistoryV2Manager
func (_mock *HistoryV2Manager) AppendHistoryNodes(ctx context.Context, request *persistence.AppendHistoryNodesRequest) (*persistence.AppendHistoryNodesResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for AppendHistoryNodes")
	}

	var r0 *persistence.AppendHistoryNodesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.AppendHistoryNodesRequest) (*persistence.AppendHistoryNodesResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.AppendHistoryNodesRequest) *persistence.AppendHistoryNodesResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persistence.AppendHistoryNodesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *persistence.AppendHistoryNodesRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HistoryV2Manager_AppendHistoryNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendHistoryNodes'
type HistoryV2Manager_AppendHistoryNodes_Call struct {
	*mock.Call
}

// AppendHistoryNodes is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.AppendHistoryNodesRequest
func (_e *HistoryV2Manager_Expecter) AppendHistoryNodes(ctx interface{}, request interface{}) *HistoryV2Manager_AppendHistoryNodes_Call {
	return &HistoryV2Manager_AppendHistoryNodes_Call{Call: _e.mock.On("AppendHistoryNodes", ctx, request)}
}

func (_c *HistoryV2Manager_AppendHistoryNodes_Call) Run(run func(ctx context.Context, request *persistence.AppendHistoryNodesRequest)) *HistoryV2Manager_AppendHistoryNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.AppendHistoryNodesRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.AppendHistoryNodesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HistoryV2Manager_AppendHistoryNodes_Call) Return(appendHistoryNodesResponse *persistence.AppendHistoryNodesResponse, err error) *HistoryV2Manager_AppendHistoryNodes_Call {
	_c.Call.Return(appendHistoryNodesResponse, err)
	return _c
}

func (_c *HistoryV2Manager_AppendHistoryNodes_Call) RunAndReturn(run func(ctx context.Context, request *persistence.AppendHistoryNodesRequest) (*persistence.AppendHistoryNodesResponse, error)) *HistoryV2Manager_AppendHistoryNodes_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type HistoryV2Manager
func (_mock *HistoryV2Manager) Close() {
	_mock.Called()
	return
}

// HistoryV2Manager_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type HistoryV2Manager_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *HistoryV2Manager_Expecter) Close() *HistoryV2Manager_Close_Call {
	return &HistoryV2Manager_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *HistoryV2Manager_Close_Call) Run(run func()) *HistoryV2Manager_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HistoryV2Manager_Close_Call) Return() *HistoryV2Manager_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *HistoryV2Manager_Close_Call) RunAndReturn(run func()) *HistoryV2Manager_Close_Call {
	_c.Run(run)
	return _c
}

// DeleteHistoryBranch provides a mock function for the type HistoryV2Manager
func (_mock *HistoryV2Manager) DeleteHistoryBranch(ctx context.Context, request *persistence.DeleteHistoryBranchRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHistoryBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.DeleteHistoryBranchRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HistoryV2Manager_DeleteHistoryBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHistoryBranch'
type HistoryV2Manager_DeleteHistoryBranch_Call struct {
	*mock.Call
}

// DeleteHistoryBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.DeleteHistoryBranchRequest
func (_e *HistoryV2Manager_Expecter) DeleteHistoryBranch(ctx interface{}, request interface{}) *HistoryV2Manager_DeleteHistoryBranch_Call {
	return &HistoryV2Manager_DeleteHistoryBranch_Call{Call: _e.mock.On("DeleteHistoryBranch", ctx, request)}
}

func (_c *HistoryV2Manager_DeleteHistoryBranch_Call) Run(run func(ctx context.Context, request *persistence.DeleteHistoryBranchRequest)) *HistoryV2Manager_DeleteHistoryBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.DeleteHistoryBranchRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.DeleteHistoryBranchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HistoryV2Manager_DeleteHistoryBranch_Call) Return(err error) *HistoryV2Manager_DeleteHistoryBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HistoryV2Manager_DeleteHistoryBranch_Call) RunAndReturn(run func(ctx context.Context, request *persistence.DeleteHistoryBranchRequest) error) *HistoryV2Manager_DeleteHistoryBranch_Call {
	_c.Call.Return(run)
	return _c
}

// ForkHistoryBranch provides a mock function for the type HistoryV2Manager
func (_mock *HistoryV2Manager) ForkHistoryBranch(ctx context.Context, request *persistence.ForkHistoryBranchRequest) (*persistence.ForkHistoryBranchResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ForkHistoryBranch")
	}

	var r0 *persistence.ForkHistoryBranchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.ForkHistoryBranchRequest) (*persistence.ForkHistoryBranchResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.ForkHistoryBranchRequest) *persistence.ForkHistoryBranchResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persistence.ForkHistoryBranchResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *persistence.ForkHistoryBranchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HistoryV2Manager_ForkHistoryBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForkHistoryBranch'
type HistoryV2Manager_ForkHistoryBranch_Call struct {
	*mock.Call
}

// ForkHistoryBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.ForkHistoryBranchRequest
func (_e *HistoryV2Manager_Expecter) ForkHistoryBranch(ctx interface{}, request interface{}) *HistoryV2Manager_ForkHistoryBranch_Call {
	return &HistoryV2Manager_ForkHistoryBranch_Call{Call: _e.mock.On("ForkHistoryBranch", ctx, request)}
}

func (_c *HistoryV2Manager_ForkHistoryBranch_Call) Run(run func(ctx context.Context, request *persistence.ForkHistoryBranchRequest)) *HistoryV2Manager_ForkHistoryBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.ForkHistoryBranchRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.ForkHistoryBranchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HistoryV2Manager_ForkHistoryBranch_Call) Return(forkHistoryBranchResponse *persistence.ForkHistoryBranchResponse, err error) *HistoryV2Manager_ForkHistoryBranch_Call {
	_c.Call.Return(forkHistoryBranchResponse, err)
	return _c
}

func (_c *HistoryV2Manager_ForkHistoryBranch_Call) RunAndReturn(run func(ctx context.Context, request *persistence.ForkHistoryBranchRequest) (*persistence.ForkHistoryBranchResponse, error)) *HistoryV2Manager_ForkHistoryBranch_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllHistoryTreeBranches provides a mock function for the type HistoryV2Manager
func (_mock *HistoryV2Manager) GetAllHistoryTreeBranches(ctx context.Context, request *persistence.GetAllHistoryTreeBranchesRequest) (*persistence.GetAllHistoryTreeBranchesResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetAllHistoryTreeBranches")
	}

	var r0 *persistence.GetAllHistoryTreeBranchesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.GetAllHistoryTreeBranchesRequest) (*persistence.GetAllHistoryTreeBranchesResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.GetAllHistoryTreeBranchesRequest) *persistence.GetAllHistoryTreeBranchesResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persistence.GetAllHistoryTreeBranchesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *persistence.GetAllHistoryTreeBranchesRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HistoryV2Manager_GetAllHistoryTreeBranches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllHistoryTreeBranches'
type HistoryV2Manager_GetAllHistoryTreeBranches_Call struct {
	*mock.Call
}

// GetAllHistoryTreeBranches is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.GetAllHistoryTreeBranchesRequest
func (_e *HistoryV2Manager_Expecter) GetAllHistoryTreeBranches(ctx interface{}, request interface{}) *HistoryV2Manager_GetAllHistoryTreeBranches_Call {
	return &HistoryV2Manager_GetAllHistoryTreeBranches_Call{Call: _e.mock.On("GetAllHistoryTreeBranches", ctx, request)}
}

func (_c *HistoryV2Manager_GetAllHistoryTreeBranches_Call) Run(run func(ctx context.Context, request *persistence.GetAllHistoryTreeBranchesRequest)) *HistoryV2Manager_GetAllHistoryTreeBranches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.GetAllHistoryTreeBranchesRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.GetAllHistoryTreeBranchesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HistoryV2Manager_GetAllHistoryTreeBranches_Call) Return(getAllHistoryTreeBranchesResponse *persistence.GetAllHistoryTreeBranchesResponse, err error) *HistoryV2Manager_GetAllHistoryTreeBranches_Call {
	_c.Call.Return(getAllHistoryTreeBranchesResponse, err)
	return _c
}

func (_c *HistoryV2Manager_GetAllHistoryTreeBranches_Call) RunAndReturn(run func(ctx context.Context, request *persistence.GetAllHistoryTreeBranchesRequest) (*persistence.GetAllHistoryTreeBranchesResponse, error)) *HistoryV2Manager_GetAllHistoryTreeBranches_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistoryTree provides a mock function for the type HistoryV2Manager
func (_mock *HistoryV2Manager) GetHistoryTree(ctx context.Context, request *persistence.GetHistoryTreeRequest) (*persistence.GetHistoryTreeResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryTree")
	}

	var r0 *persistence.GetHistoryTreeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.GetHistoryTreeRequest) (*persistence.GetHistoryTreeResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.GetHistoryTreeRequest) *persistence.GetHistoryTreeResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persistence.GetHistoryTreeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *persistence.GetHistoryTreeRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HistoryV2Manager_GetHistoryTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoryTree'
type HistoryV2Manager_GetHistoryTree_Call struct {
	*mock.Call
}

// GetHistoryTree is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.GetHistoryTreeRequest
func (_e *HistoryV2Manager_Expecter) GetHistoryTree(ctx interface{}, request interface{}) *HistoryV2Manager_GetHistoryTree_Call {
	return &HistoryV2Manager_GetHistoryTree_Call{Call: _e.mock.On("GetHistoryTree", ctx, request)}
}

func (_c *HistoryV2Manager_GetHistoryTree_Call) Run(run func(ctx context.Context, request *persistence.GetHistoryTreeRequest)) *HistoryV2Manager_GetHistoryTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.GetHistoryTreeRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.GetHistoryTreeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HistoryV2Manager_GetHistoryTree_Call) Return(getHistoryTreeResponse *persistence.GetHistoryTreeResponse, err error) *HistoryV2Manager_GetHistoryTree_Call {
	_c.Call.Return(getHistoryTreeResponse, err)
	return _c
}

func (_c *HistoryV2Manager_GetHistoryTree_Call) RunAndReturn(run func(ctx context.Context, request *persistence.GetHistoryTreeRequest) (*persistence.GetHistoryTreeResponse, error)) *HistoryV2Manager_GetHistoryTree_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type HistoryV2Manager
func (_mock *HistoryV2Manager) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// HistoryV2Manager_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type HistoryV2Manager_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *HistoryV2Manager_Expecter) GetName() *HistoryV2Manager_GetName_Call {
	return &HistoryV2Manager_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *HistoryV2Manager_GetName_Call) Run(run func()) *HistoryV2Manager_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HistoryV2Manager_GetName_Call) Return(s string) *HistoryV2Manager_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *HistoryV2Manager_GetName_Call) RunAndReturn(run func() string) *HistoryV2Manager_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// ReadHistoryBranch provides a mock function for the type HistoryV2Manager
func (_mock *HistoryV2Manager) ReadHistoryBranch(ctx context.Context, request *persistence.ReadHistoryBranchRequest) (*persistence.ReadHistoryBranchResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ReadHistoryBranch")
	}

	var r0 *persistence.ReadHistoryBranchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.ReadHistoryBranchRequest) (*persistence.ReadHistoryBranchResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.ReadHistoryBranchRequest) *persistence.ReadHistoryBranchResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persistence.ReadHistoryBranchResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *persistence.ReadHistoryBranchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HistoryV2Manager_ReadHistoryBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadHistoryBranch'
type HistoryV2Manager_ReadHistoryBranch_Call struct {
	*mock.Call
}

// ReadHistoryBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.ReadHistoryBranchRequest
func (_e *HistoryV2Manager_Expecter) ReadHistoryBranch(ctx interface{}, request interface{}) *HistoryV2Manager_ReadHistoryBranch_Call {
	return &HistoryV2Manager_ReadHistoryBranch_Call{Call: _e.mock.On("ReadHistoryBranch", ctx, request)}
}

func (_c *HistoryV2Manager_ReadHistoryBranch_Call) Run(run func(ctx context.Context, request *persistence.ReadHistoryBranchRequest)) *HistoryV2Manager_ReadHistoryBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.ReadHistoryBranchRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.ReadHistoryBranchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HistoryV2Manager_ReadHistoryBranch_Call) Return(readHistoryBranchResponse *persistence.ReadHistoryBranchResponse, err error) *HistoryV2Manager_ReadHistoryBranch_Call {
	_c.Call.Return(readHistoryBranchResponse, err)
	return _c
}

func (_c *HistoryV2Manager_ReadHistoryBranch_Call) RunAndReturn(run func(ctx context.Context, request *persistence.ReadHistoryBranchRequest) (*persistence.ReadHistoryBranchResponse, error)) *HistoryV2Manager_ReadHistoryBranch_Call {
	_c.Call.Return(run)
	return _c
}

// ReadHistoryBranchByBatch provides a mock function for the type HistoryV2Manager
func (_mock *HistoryV2Manager) ReadHistoryBranchByBatch(ctx context.Context, request *persistence.ReadHistoryBranchRequest) (*persistence.ReadHistoryBranchByBatchResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ReadHistoryBranchByBatch")
	}

	var r0 *persistence.ReadHistoryBranchByBatchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.ReadHistoryBranchRequest) (*persistence.ReadHistoryBranchByBatchResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.ReadHistoryBranchRequest) *persistence.ReadHistoryBranchByBatchResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persistence.ReadHistoryBranchByBatchResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *persistence.ReadHistoryBranchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HistoryV2Manager_ReadHistoryBranchByBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadHistoryBranchByBatch'
type HistoryV2Manager_ReadHistoryBranchByBatch_Call struct {
	*mock.Call
}

// ReadHistoryBranchByBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.ReadHistoryBranchRequest
func (_e *HistoryV2Manager_Expecter) ReadHistoryBranchByBatch(ctx interface{}, request interface{}) *HistoryV2Manager_ReadHistoryBranchByBatch_Call {
	return &HistoryV2Manager_ReadHistoryBranchByBatch_Call{Call: _e.mock.On("ReadHistoryBranchByBatch", ctx, request)}
}

func (_c *HistoryV2Manager_ReadHistoryBranchByBatch_Call) Run(run func(ctx context.Context, request *persistence.ReadHistoryBranchRequest)) *HistoryV2Manager_ReadHistoryBranchByBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.ReadHistoryBranchRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.ReadHistoryBranchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HistoryV2Manager_ReadHistoryBranchByBatch_Call) Return(readHistoryBranchByBatchResponse *persistence.ReadHistoryBranchByBatchResponse, err error) *HistoryV2Manager_ReadHistoryBranchByBatch_Call {
	_c.Call.Return(readHistoryBranchByBatchResponse, err)
	return _c
}

func (_c *HistoryV2Manager_ReadHistoryBranchByBatch_Call) RunAndReturn(run func(ctx context.Context, request *persistence.ReadHistoryBranchRequest) (*persistence.ReadHistoryBranchByBatchResponse, error)) *HistoryV2Manager_ReadHistoryBranchByBatch_Call {
	_c.Call.Return(run)
	return _c
}

// ReadRawHistoryBranch provides a mock function for the type HistoryV2Manager
func (_mock *HistoryV2Manager) ReadRawHistoryBranch(ctx context.Context, request *persistence.ReadHistoryBranchRequest) (*persistence.ReadRawHistoryBranchResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ReadRawHistoryBranch")
	}

	var r0 *persistence.ReadRawHistoryBranchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.ReadHistoryBranchRequest) (*persistence.ReadRawHistoryBranchResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.ReadHistoryBranchRequest) *persistence.ReadRawHistoryBranchResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persistence.ReadRawHistoryBranchResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *persistence.ReadHistoryBranchRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HistoryV2Manager_ReadRawHistoryBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRawHistoryBranch'
type HistoryV2Manager_ReadRawHistoryBranch_Call struct {
	*mock.Call
}

// ReadRawHistoryBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.ReadHistoryBranchRequest
func (_e *HistoryV2Manager_Expecter) ReadRawHistoryBranch(ctx interface{}, request interface{}) *HistoryV2Manager_ReadRawHistoryBranch_Call {
	return &HistoryV2Manager_ReadRawHistoryBranch_Call{Call: _e.mock.On("ReadRawHistoryBranch", ctx, request)}
}

func (_c *HistoryV2Manager_ReadRawHistoryBranch_Call) Run(run func(ctx context.Context, request *persistence.ReadHistoryBranchRequest)) *HistoryV2Manager_ReadRawHistoryBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.ReadHistoryBranchRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.ReadHistoryBranchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HistoryV2Manager_ReadRawHistoryBranch_Call) Return(readRawHistoryBranchResponse *persistence.ReadRawHistoryBranchResponse, err error) *HistoryV2Manager_ReadRawHistoryBranch_Call {
	_c.Call.Return(readRawHistoryBranchResponse, err)
	return _c
}

func (_c *HistoryV2Manager_ReadRawHistoryBranch_Call) RunAndReturn(run func(ctx context.Context, request *persistence.ReadHistoryBranchRequest) (*persistence.ReadRawHistoryBranchResponse, error)) *HistoryV2Manager_ReadRawHistoryBranch_Call {
	_c.Call.Return(run)
	return _c
}
