// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/uber/cadence/common/persistence"
)

// NewMetadataManager creates a new instance of MetadataManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetadataManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetadataManager {
	mock := &MetadataManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MetadataManager is an autogenerated mock type for the DomainManager type
type MetadataManager struct {
	mock.Mock
}

type MetadataManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MetadataManager) EXPECT() *MetadataManager_Expecter {
	return &MetadataManager_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MetadataManager
func (_mock *MetadataManager) Close() {
	_mock.Called()
	return
}

// MetadataManager_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MetadataManager_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MetadataManager_Expecter) Close() *MetadataManager_Close_Call {
	return &MetadataManager_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MetadataManager_Close_Call) Run(run func()) *MetadataManager_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetadataManager_Close_Call) Return() *MetadataManager_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MetadataManager_Close_Call) RunAndReturn(run func()) *MetadataManager_Close_Call {
	_c.Run(run)
	return _c
}

// CreateDomain provides a mock function for the type MetadataManager
func (_mock *MetadataManager) CreateDomain(ctx context.Context, request *persistence.CreateDomainRequest) (*persistence.CreateDomainResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateDomain")
	}

	var r0 *persistence.CreateDomainResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.CreateDomainRequest) (*persistence.CreateDomainResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.CreateDomainRequest) *persistence.CreateDomainResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persistence.CreateDomainResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *persistence.CreateDomainRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetadataManager_CreateDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDomain'
type MetadataManager_CreateDomain_Call struct {
	*mock.Call
}

// CreateDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.CreateDomainRequest
func (_e *MetadataManager_Expecter) CreateDomain(ctx interface{}, request interface{}) *MetadataManager_CreateDomain_Call {
	return &MetadataManager_CreateDomain_Call{Call: _e.mock.On("CreateDomain", ctx, request)}
}

func (_c *MetadataManager_CreateDomain_Call) Run(run func(ctx context.Context, request *persistence.CreateDomainRequest)) *MetadataManager_CreateDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.CreateDomainRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.CreateDomainRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetadataManager_CreateDomain_Call) Return(createDomainResponse *persistence.CreateDomainResponse, err error) *MetadataManager_CreateDomain_Call {
	_c.Call.Return(createDomainResponse, err)
	return _c
}

func (_c *MetadataManager_CreateDomain_Call) RunAndReturn(run func(ctx context.Context, request *persistence.CreateDomainRequest) (*persistence.CreateDomainResponse, error)) *MetadataManager_CreateDomain_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDomain provides a mock function for the type MetadataManager
func (_mock *MetadataManager) DeleteDomain(ctx context.Context, request *persistence.DeleteDomainRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.DeleteDomainRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MetadataManager_DeleteDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDomain'
type MetadataManager_DeleteDomain_Call struct {
	*mock.Call
}

// DeleteDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.DeleteDomainRequest
func (_e *MetadataManager_Expecter) DeleteDomain(ctx interface{}, request interface{}) *MetadataManager_DeleteDomain_Call {
	return &MetadataManager_DeleteDomain_Call{Call: _e.mock.On("DeleteDomain", ctx, request)}
}

func (_c *MetadataManager_DeleteDomain_Call) Run(run func(ctx context.Context, request *persistence.DeleteDomainRequest)) *MetadataManager_DeleteDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.DeleteDomainRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.DeleteDomainRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetadataManager_DeleteDomain_Call) Return(err error) *MetadataManager_DeleteDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MetadataManager_DeleteDomain_Call) RunAndReturn(run func(ctx context.Context, request *persistence.DeleteDomainRequest) error) *MetadataManager_DeleteDomain_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDomainByName provides a mock function for the type MetadataManager
func (_mock *MetadataManager) DeleteDomainByName(ctx context.Context, request *persistence.DeleteDomainByNameRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDomainByName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.DeleteDomainByNameRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MetadataManager_DeleteDomainByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDomainByName'
type MetadataManager_DeleteDomainByName_Call struct {
	*mock.Call
}

// DeleteDomainByName is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.DeleteDomainByNameRequest
func (_e *MetadataManager_Expecter) DeleteDomainByName(ctx interface{}, request interface{}) *MetadataManager_DeleteDomainByName_Call {
	return &MetadataManager_DeleteDomainByName_Call{Call: _e.mock.On("DeleteDomainByName", ctx, request)}
}

func (_c *MetadataManager_DeleteDomainByName_Call) Run(run func(ctx context.Context, request *persistence.DeleteDomainByNameRequest)) *MetadataManager_DeleteDomainByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.DeleteDomainByNameRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.DeleteDomainByNameRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetadataManager_DeleteDomainByName_Call) Return(err error) *MetadataManager_DeleteDomainByName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MetadataManager_DeleteDomainByName_Call) RunAndReturn(run func(ctx context.Context, request *persistence.DeleteDomainByNameRequest) error) *MetadataManager_DeleteDomainByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetDomain provides a mock function for the type MetadataManager
func (_mock *MetadataManager) GetDomain(ctx context.Context, request *persistence.GetDomainRequest) (*persistence.GetDomainResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetDomain")
	}

	var r0 *persistence.GetDomainResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.GetDomainRequest) (*persistence.GetDomainResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.GetDomainRequest) *persistence.GetDomainResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persistence.GetDomainResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *persistence.GetDomainRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetadataManager_GetDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDomain'
type MetadataManager_GetDomain_Call struct {
	*mock.Call
}

// GetDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.GetDomainRequest
func (_e *MetadataManager_Expecter) GetDomain(ctx interface{}, request interface{}) *MetadataManager_GetDomain_Call {
	return &MetadataManager_GetDomain_Call{Call: _e.mock.On("GetDomain", ctx, request)}
}

func (_c *MetadataManager_GetDomain_Call) Run(run func(ctx context.Context, request *persistence.GetDomainRequest)) *MetadataManager_GetDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.GetDomainRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.GetDomainRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetadataManager_GetDomain_Call) Return(getDomainResponse *persistence.GetDomainResponse, err error) *MetadataManager_GetDomain_Call {
	_c.Call.Return(getDomainResponse, err)
	return _c
}

func (_c *MetadataManager_GetDomain_Call) RunAndReturn(run func(ctx context.Context, request *persistence.GetDomainRequest) (*persistence.GetDomainResponse, error)) *MetadataManager_GetDomain_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadata provides a mock function for the type MetadataManager
func (_mock *MetadataManager) GetMetadata(ctx context.Context) (*persistence.GetMetadataResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 *persistence.GetMetadataResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*persistence.GetMetadataResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *persistence.GetMetadataResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persistence.GetMetadataResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetadataManager_GetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadata'
type MetadataManager_GetMetadata_Call struct {
	*mock.Call
}

// GetMetadata is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MetadataManager_Expecter) GetMetadata(ctx interface{}) *MetadataManager_GetMetadata_Call {
	return &MetadataManager_GetMetadata_Call{Call: _e.mock.On("GetMetadata", ctx)}
}

func (_c *MetadataManager_GetMetadata_Call) Run(run func(ctx context.Context)) *MetadataManager_GetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MetadataManager_GetMetadata_Call) Return(getMetadataResponse *persistence.GetMetadataResponse, err error) *MetadataManager_GetMetadata_Call {
	_c.Call.Return(getMetadataResponse, err)
	return _c
}

func (_c *MetadataManager_GetMetadata_Call) RunAndReturn(run func(ctx context.Context) (*persistence.GetMetadataResponse, error)) *MetadataManager_GetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MetadataManager
func (_mock *MetadataManager) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MetadataManager_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MetadataManager_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MetadataManager_Expecter) GetName() *MetadataManager_GetName_Call {
	return &MetadataManager_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MetadataManager_GetName_Call) Run(run func()) *MetadataManager_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetadataManager_GetName_Call) Return(s string) *MetadataManager_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MetadataManager_GetName_Call) RunAndReturn(run func() string) *MetadataManager_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// ListDomains provides a mock function for the type MetadataManager
func (_mock *MetadataManager) ListDomains(ctx context.Context, request *persistence.ListDomainsRequest) (*persistence.ListDomainsResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ListDomains")
	}

	var r0 *persistence.ListDomainsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.ListDomainsRequest) (*persistence.ListDomainsResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.ListDomainsRequest) *persistence.ListDomainsResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*persistence.ListDomainsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *persistence.ListDomainsRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MetadataManager_ListDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDomains'
type MetadataManager_ListDomains_Call struct {
	*mock.Call
}

// ListDomains is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.ListDomainsRequest
func (_e *MetadataManager_Expecter) ListDomains(ctx interface{}, request interface{}) *MetadataManager_ListDomains_Call {
	return &MetadataManager_ListDomains_Call{Call: _e.mock.On("ListDomains", ctx, request)}
}

func (_c *MetadataManager_ListDomains_Call) Run(run func(ctx context.Context, request *persistence.ListDomainsRequest)) *MetadataManager_ListDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.ListDomainsRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.ListDomainsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetadataManager_ListDomains_Call) Return(listDomainsResponse *persistence.ListDomainsResponse, err error) *MetadataManager_ListDomains_Call {
	_c.Call.Return(listDomainsResponse, err)
	return _c
}

func (_c *MetadataManager_ListDomains_Call) RunAndReturn(run func(ctx context.Context, request *persistence.ListDomainsRequest) (*persistence.ListDomainsResponse, error)) *MetadataManager_ListDomains_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDomain provides a mock function for the type MetadataManager
func (_mock *MetadataManager) UpdateDomain(ctx context.Context, request *persistence.UpdateDomainRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDomain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *persistence.UpdateDomainRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MetadataManager_UpdateDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDomain'
type MetadataManager_UpdateDomain_Call struct {
	*mock.Call
}

// UpdateDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - request *persistence.UpdateDomainRequest
func (_e *MetadataManager_Expecter) UpdateDomain(ctx interface{}, request interface{}) *MetadataManager_UpdateDomain_Call {
	return &MetadataManager_UpdateDomain_Call{Call: _e.mock.On("UpdateDomain", ctx, request)}
}

func (_c *MetadataManager_UpdateDomain_Call) Run(run func(ctx context.Context, request *persistence.UpdateDomainRequest)) *MetadataManager_UpdateDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *persistence.UpdateDomainRequest
		if args[1] != nil {
			arg1 = args[1].(*persistence.UpdateDomainRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MetadataManager_UpdateDomain_Call) Return(err error) *MetadataManager_UpdateDomain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MetadataManager_UpdateDomain_Call) RunAndReturn(run func(ctx context.Context, request *persistence.UpdateDomainRequest) error) *MetadataManager_UpdateDomain_Call {
	_c.Call.Return(run)
	return _c
}
